### ISSUE TITLE
Additional Files

### ISSUE THREAD

**Issue by ghost** [jhester/DistributedGA#1]
We need to split up the server.py into multiple files again, perhaps one for player connection handler and observer connection handler?

**Comment by jhester** [comment]
Yeah maybe we should put each class in a file like in JAVA? I saw that you already split it up a bit in the server.py.

**Comment by ghost** [comment]
Some parts are not contained in a class though, really just the basic code for each "section" (client/server/observer) so we could create separate files for that and separate files for classes.  I don't think there will be anything wrong with many files, then we can import the classes in both the client and server for instance.

**Comment by jhester** [comment]
Alright that sounds good.
