### ISSUE TITLE
Client AI

### ISSUE THREAD

**Issue by ghost** [jhester/DistributedGA#14]
Some balance is needed in the client AI now because players with a low courage tend to survive to the end and then never attack...  I'm thinking the server is done now, so I'll start focusing on the client?

**Comment by anander** [comment]
Maybe we should set it so the lowest courage is 50. That way they would attack more often.

**Comment by ghost** [comment]
I think courage should take health in to consideration, instead of running from everyone.

**Comment by ghost** [comment]
Clients now use all 4 variables, they each "influence" the clients target equally.
