### ISSUE TITLE
Server synchronization

### ISSUE THREAD

**Issue by ghost** [jhester/DistributedGA#15]
Right now when the server starts a round it just sets a flag and waits for the clients to start playing, which means they end up starting at random times, should we bother putting an event in to have all clients start at the same time? or is it not worth the effort?

**Comment by jhester** [comment]
I dont think its worth it right now, cause it may not be a quick fix at all. We can just concentrate on other stuff.

**Comment by ghost** [comment]
Ok lets focus on making it look good
