### ISSUE TITLE
Condor

### ISSUE THREAD

**Issue by ghost** [jhester/DistributedGA#16]
We might have to look into another source of clients, I have been having trouble getting condor to give more than 20-30 clients.

**Comment by ghost** [comment]
Ok so I created a script to launch 30 clients in 30 different threads on 1 dragon machine, so with about 4 shells we get enough clients... the dragons seems to be handling the load well, but I'm not sure yet.

**Comment by jhester** [comment]
The dragons are supposed to be really fast. What if we multiple dragons?  Should we ask Goasguen about the condor problems?

**Comment by ghost** [comment]
I found a python script that will basically do a recvall(), but after trying to have 100 clients on the same dragon + the server + the observer... I can't seem to get any sockets to connect anywhere lol

**Comment by ghost** [comment]
recvall function is commited far less drops but we are still getting a couple...
