### ISSUE TITLE
Receiving data

### ISSUE THREAD

**Issue by ghost** [jhester/DistributedGA#18]
We are still have problems getting data from the socket.  recv doesn't always get all the data, which then messes pickle up.  If we fix this then I think our client dropping issues will stop.  Right now if the same computer is hosting the server and clients they never drop, which means we have a network issue

**Comment by jhester** [comment]
Should we get a script that will resend if the data is incomplete?

**Comment by jhester** [comment]
So from what I read using pickle on a network is both inconsistent , and unsafe. A lot of people had the same issues we do.

**Comment by ghost** [comment]
I found a script to act like a recvall function, plus if pickle fails to load (not too too often) the client handles that correctly (tells server it didn't get information)

Client dropping issue seems to be completely solved.
