### ISSUE TITLE
Observer not getting some info

### ISSUE THREAD

**Issue by ghost** [jhester/DistributedGA#3]
When creating additional players after the observer it doesn't seem to get data on the new player.  Also there seems to be lots of lag (I blame pickle) after you add more than 1 player.

**Comment by ghost** [comment]
We need a 'packer' function for players like we do for the map.  I created a getDictionary() function in the player manager, I feel like the player manager should hold a function that packs all changed player info into a string.  This dictionary function should be changed, if we make a pack function in the player then there is no need to return a dictionary...

**Comment by anander** [comment]
Yeah why need a dictionary when were just packing everything into a string? All it needs is pack, unpack and update which will take the unpacked string and use it to make changes to the players list

**Comment by ghost** [comment]
the getDictionary is a placeholder until we write a packer/unpacker function, I didn't want to leave the program in a not working state

**Comment by jhester** [comment]
Right now the observer gets all the data it needs until we want to get things like player death etc.

**Comment by ghost** [comment]
Yeah, I guess this issue is closed... sort of
