### ISSUE TITLE
Packer

### ISSUE THREAD

**Issue by anander** [jhester/DistributedGA#6]
We need a class for packing the map into a string and a class for packing the players into a string that need updating.

**Comment by ghost** [comment]
Either 1 per class, or 1 that handles all classes. Packer should be able to pack into a string, unpack into a class, or unpack a string and update an existing class. I'm not sure the best way to do this, we need condor so downloading new modules isn't really a good idea (right?) we could use 'struct' but I think it has site limitations. Struct seems to be designed for single variables which might work for the players as they are just id, xpos, ypos, health (int,int,int,byte) right now.

We might need to just write our own function to pack into bytes and create a string...

**Comment by jhester** [comment]
Lets just use a simple string parser (we have to write it ourselves), tokenize the variables into an array and pass it into a struct or class.

**Comment by ghost** [comment]
Pickle seems to be working, provided we only pickle a list of numbers...
