### ISSUE TITLE
(Un)Packer

### ISSUE THREAD

**Issue by ghost** [jhester/DistributedGA#7]
We need a packer/unpacker class (either 1 per class, or 1 that handles all classes).  Packer should be able to pack into a string, unpack into a class, or unpack a string and update an existing class.  I'm not sure the best way to do this, we need condor so downloading new modules isn't really a good idea (right?) we could use 'struct' but I think it has site limitations.  Struct seems to be designed for single variables which might work for the players as they are just id, xpos, ypos, health (int,int,int,byte) right now.

We might need to just write our own function to pack into bytes and create a string...

**Comment by jhester** [comment]
That seems the best option to me, since we have to use python 2.4 (because of condor) we may need to have a lot of custom functions.
