### ISSUE TITLE
observer...

### ISSUE THREAD

**Issue by anander** [jhester/DistributedGA#9]
is giving me a connection refused error. is there something im not doing right in running it? Maybe someone can put some run instructions in the readme. thanks!

**Comment by ghost** [comment]
Make sure you are connecting to the server, it should only be 1 server 1 observer (it might be able to handle multiple observers but I haven't tested that) and 1+ clients.

I am getting an EOF error from pickle when I try to run the observer on a different computer, but it works just fine if all clients/server are on the same gecko machine...

**Comment by jhester** [comment]
Yeah I was able to run the whole thing on my Macbook pro with multiple clients.  Localhost it.

**Comment by ghost** [comment]
It seems to be a problem reading all the data on the observer side.
